version: '3.3'

volumes:
  postgres_data:
  static_data:
  media_data:

services:
  db:
    image: postgres:13.0-alpine
    container_name: linkvault-db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    build: ./web
    container_name: linkvault-web
    env_file: .env
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    depends_on:
      - db
    ports:
      - 8000:8000
    links:
      - db
    restart: always
    command: sh -c "python3 manage.py makemigrations &&
                    python3 manage.py migrate &&
                    python3 manage.py collectstatic --noinput &&
                    gunicorn linkvault.wsgi:application --bind 0.0.0.0:8000 --timeout 120"
      
  nginx:
    image: nginx:latest
    container_name: linkvault-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/static
      - media_data:/app/media
    ports:
      - 80:80
    restart: always
