# Generated by Django 4.2.20 on 2025-04-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_link_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='favicon_image',
            field=models.ImageField(blank=True, default='defaults/favicon_default.png', null=True, upload_to='favicons/'),
        ),
    ]
